# FROM eclipse-temurin:17-jre-jammy

# WORKDIR /app

# # 라이브러리 복사
# COPY libs ./libs
# COPY src ./src

# # 컴파일
# RUN javac -cp "libs/*" src/MskProducer.java

# # 실행
# CMD ["java", "-cp", "src:libs/*", "MskProducer"]
