[backend]
# LoRa Basics Station backend
type="basic_station"

[backend.basic_station]
bind=":3001"  # Basics Station WebSocket 포트
# tls_cert="/etc/chirpstack-gateway-bridge/certs/cert.pem"
# tls_key="/etc/chirpstack-gateway-bridge/certs/key.pem"

# Configuration for CUPS (optional, can skip for now)
# cups_uri=""

# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""
